### ISSUE TITLE
The code cannot run

### ISSUE THREAD

**Issue by yzcv** [MarioniLab/FurtherMNN2018#12]
Hi,

I am a novice in bioinformatics field. And I am very attracted by your MNN work. But I fell very confused as I can not run your code  normalizePancreas.R in MNN2017-master/Pancreas. After all the required packages installed, the error is as follows,

> Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘isSpike<-’ for signature ‘"SingleCellExperiment", "missing"’

Could you please provide a hint to fix this issue? Thanks a bunch.

**Comment by LTLA** [comment]
That code is long dead. Try https://osca.bioconductor.org/merged-pancreas.html instead.
