### ISSUE TITLE
The mkdir command is missing for the download_data.sh in haematopoiesis folder

### ISSUE THREAD

**Issue by mt1022** [MarioniLab/FurtherMNN2018#2]
What about add a line like this?

```
if [ ! -d "raw_data" ]; then mkdir raw_data; fi
```

**Comment by LTLA** [comment]
I was actually going to transition all of these to use the excellent _BiocFileCache_ facility from Bioconductor. You can make a PR if you like, but I'm going to delete these files anyway eventually.

**Comment by mt1022** [comment]
It is quite obvious for readers. Let's leave it as is and wait for the BiocFileCache version.

**Comment by LTLA** [comment]
The transition to _BiocFileCache_ is mostly complete - I am still waiting for our institute to fix some security certificates related to the processed data files for the pancreas dataset, so `pancreas/prepareData.R` won't work properly right now. Everything else should be functional, so I'll close this.
