### ISSUE TITLE
Question about "droplet/prepareData.R"

### ISSUE THREAD

**Issue by sunkh1026** [MarioniLab/FurtherMNN2018#3]
While running

`clusters <- quickCluster(sce.68, min.mean=0.1, block=blocks, method="igraph", block.BPPARAM=MulticoreParam(2))`

it showed

> Error in .local(x, ...) : 
  unused arguments (block = blocks, block.BPPARAM = MulticoreParam(2))

How could it be fixed? Thanks!

**Comment by LTLA** [comment]
Session information, etc. 

http://www.bioconductor.org/help/support/posting-guide/

Requires BioC-devel and https://github.com/MarioniLab/scran.
