### ISSUE TITLE
Question about "pancreas/prepareData.R"

### ISSUE THREAD

**Issue by ssscj** [MarioniLab/FurtherMNN2018#8]
thanks for developing this package
While running 
`sce.emtab6<- computeSumFactors(sce.emtab,clusters=clusters1,min.mean=1)`
it showed 
> Warning message:
> In .local(x, ...) : zero spike-in counts during spike-in normalization

and while running:
`sce.emtab3 <- normalize(sce.emtab2,return_log=FALSE)`
it showed
>Error in .local(object, ...) : 
>size factors should be positive real numbers

how could I fix it? Thank you!

**Comment by LTLA** [comment]
1. The warning arises from `computeSpikeFactors`, not `computeSumFactors`.
2. You can skip the `normalize()` step, everything gets re-normalized in `plotCorrections.R` anyway.

**Comment by ssscj** [comment]
Thanks for your reply. I'm sorry for my mistake. I have one more question.
Can I skip the `computeSpikeFactors()` step instead of `normalize()` step, because I think the spike-ins are not important in the analysis.

**Comment by LTLA** [comment]
The spike-ins are used for modelling variability in each batch. Now, that's not critical, but we already have the spike-ins in this data set, so why not use them? If you're referring to your own data set that doesn't have spike-ins, you can consider alternative strategies as described [here](http://bioconductor.org/packages/devel/workflows/vignettes/simpleSingleCell/inst/doc/var.html#32_when_spike-ins_are_unavailable).
